version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: nbp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: mojabaza
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initDB.sql:/docker-entrypoint-initdb.d/initDB.sql

volumes:
  postgres_data:
